version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /root/nginx/certs/www:/var/www/certbot
      - /root/nginx/certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done'"
